#!/usr/bin/env python3
"""
RUGGY REWARDS build tool — mechanically split or merge the site files.

Usage:
    python3 build.py split <single-file.html> [outdir]
        Extracts every <style> block into styles.css and every inline
        <script> block into app.js (document order preserved), and writes
        a clean index.html that links both. Verifies the result.

    python3 build.py merge <index.html> [outdir]
        Reads index.html plus styles.css and app.js from the same folder
        and produces single-file.html — handy for sharing the whole site
        as one file (e.g. for an AI code review).

Both directions preserve document order, so cascade and execution
semantics are unchanged. No dependencies; uses node for JS syntax
verification if it's installed, otherwise skips that check.
"""

import re
import shutil
import subprocess
import sys
from pathlib import Path

STYLE_RE = re.compile(r'[ \t]*<style[^>]*>(.*?)</style>\n?', re.S)
INLINE_SCRIPT_RE = re.compile(r'[ \t]*<script(?![^>]*\bsrc=)[^>]*>(.*?)</script>\n?', re.S)
APP_SCRIPT_TAG = '<script defer src="app.js"></script>'
CSS_LINK_TAG = '<link rel="stylesheet" href="styles.css">'

CSS_HEADER = (
    "/* RUGGY REWARDS - stylesheet (generated by build.py split).\n"
    "   Style blocks appear in original document order; cascade unchanged. */\n"
)
JS_HEADER = (
    "/* RUGGY REWARDS - application JS (generated by build.py split).\n"
    "   Script blocks appear in original document order. Loaded with\n"
    "   <script defer> so the DOM is fully parsed before execution. */\n"
)


def outdent(block: str) -> str:
    # strip() (not just newlines) drops the trailing indentation captured
    # from before the closing </script>/</style> tag
    return re.sub(r'^        ', '', block.strip(), flags=re.M)


def node_check(js_path: Path) -> str:
    node = shutil.which('node')
    if not node:
        return "skipped (node not installed)"
    r = subprocess.run([node, '--check', str(js_path)], capture_output=True, text=True)
    return "OK" if r.returncode == 0 else f"SYNTAX ERROR\n{r.stderr.strip()}"


def split(src_path: Path, outdir: Path) -> int:
    html = src_path.read_text(encoding='utf-8')

    styles = STYLE_RE.findall(html)
    scripts = INLINE_SCRIPT_RE.findall(html)
    if not styles and not scripts:
        print("Nothing to split: no inline <style> or <script> blocks found.")
        return 1

    # styles.css
    css_parts = [CSS_HEADER]
    for i, block in enumerate(styles, 1):
        css_parts.append(f"\n/* ===== STYLE BLOCK {i} ===== */")
        css_parts.append(outdent(block))
    css = '\n'.join(css_parts) + '\n'

    # app.js
    js_parts = [JS_HEADER]
    for i, block in enumerate(scripts, 1):
        js_parts.append(f"\n/* ===== SCRIPT BLOCK {i} ===== */")
        js_parts.append(outdent(block))
    js = '\n'.join(js_parts) + '\n'

    # index.html: first <style> becomes the css link, the rest vanish;
    # all inline scripts vanish; app.js tag goes after the last external
    # head script (or before </head> if there are none).
    first_style = STYLE_RE.search(html)
    if first_style:
        html = html[:first_style.start()] + f'    {CSS_LINK_TAG}\n' + html[first_style.end():]
        html = STYLE_RE.sub('', html)
    html = INLINE_SCRIPT_RE.sub('', html)

    head_end = html.index('</head>')
    ext_scripts = list(re.finditer(r'[ \t]*<script[^>]*\bsrc="[^"]*"[^>]*>\s*</script>\n?', html[:head_end]))
    if ext_scripts:
        insert_at = ext_scripts[-1].end()
    else:
        insert_at = head_end
    html = html[:insert_at] + f'    {APP_SCRIPT_TAG}\n' + html[insert_at:]

    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / 'styles.css').write_text(css, encoding='utf-8')
    (outdir / 'app.js').write_text(js, encoding='utf-8')
    (outdir / 'index.html').write_text(html, encoding='utf-8')

    # ----- verification -----
    print(f"split: {len(styles)} style block(s) -> styles.css ({len(css)} chars)")
    print(f"       {len(scripts)} script block(s) -> app.js ({len(js)} chars)")
    print(f"       index.html: {len(html)} chars")
    problems = 0

    leftover_style = bool(re.search(r'<style', html))
    leftover_script = bool(INLINE_SCRIPT_RE.search(html))
    print(f"check: no inline <style> remains: {'OK' if not leftover_style else 'FAIL'}")
    print(f"check: no inline <script> remains: {'OK' if not leftover_script else 'FAIL'}")
    problems += leftover_style + leftover_script

    bal = css.count('{') - css.count('}')
    print(f"check: CSS brace balance: {'OK' if bal == 0 else f'FAIL ({bal:+d})'}")
    problems += bal != 0

    js_check = node_check(outdir / 'app.js')
    print(f"check: app.js syntax (catches cross-block redeclarations): {js_check}")
    problems += js_check.startswith('SYNTAX')

    # ids present in the original but absent from the new markup must all
    # be accounted for inside app.js (i.e. they live in JS template strings)
    orig_ids = set(re.findall(r'id="([^"]+)"', src_path.read_text(encoding='utf-8')))
    new_ids = set(re.findall(r'id="([^"]+)"', html))
    moved = sorted(orig_ids - new_ids)
    lost = [i for i in moved if i not in js]
    print(f"check: ids moved into JS templates: {len(moved)}; genuinely lost: "
          f"{'none' if not lost else lost}")
    problems += bool(lost)

    print("\nresult:", "CLEAN SPLIT" if problems == 0 else f"{problems} PROBLEM(S) - do not deploy")
    return 0 if problems == 0 else 1


def merge(index_path: Path, outdir: Path) -> int:
    """Inline every LOCAL stylesheet <link> and <script src> (document
    order preserved) into one single-file HTML. External (http/https)
    resources are left as-is."""
    folder = index_path.parent
    html = index_path.read_text(encoding='utf-8')

    strip = re.compile(
        r'/\* RUGGY REWARDS - (?:stylesheet|application JS) \(generated by build\.py split\)\.\n'
        r'(?:[^*]|\*(?!/))*\*/\n*'
        r'|/\* ===== (?:STYLE|SCRIPT) BLOCK \d+ ===== \*/\n*'
    )

    def indent(text):
        return re.sub(r'^(?=.)', '        ', text.rstrip('\n'), flags=re.M)

    inlined = {'css': 0, 'js': 0}

    def css_repl(m):
        href = m.group(1)
        if href.startswith(('http://', 'https://', '//')):
            return m.group(0)
        f = folder / href
        if not f.exists():
            print(f"warning: {href} not found, leaving link in place")
            return m.group(0)
        inlined['css'] += 1
        return f'    <style>\n{indent(strip.sub("", f.read_text(encoding="utf-8")))}\n    </style>\n'

    def js_repl(m):
        s = m.group(1)
        if s.startswith(('http://', 'https://', '//')):
            return m.group(0)
        f = folder / s
        if not f.exists():
            print(f"warning: {s} not found, leaving script in place")
            return m.group(0)
        inlined['js'] += 1
        return f'    <script>\n{indent(strip.sub("", f.read_text(encoding="utf-8")))}\n    </script>\n'

    html = re.sub(r'[ \t]*<link rel="stylesheet" href="([^"]+)">\n?', css_repl, html)
    html = re.sub(r'[ \t]*<script[^>]*\bsrc="([^"]+)"[^>]*>\s*</script>\n?', js_repl, html)

    if not inlined['css'] and not inlined['js']:
        print("nothing local to inline - was index.html produced by 'split'?")
        return 1

    outdir.mkdir(parents=True, exist_ok=True)
    out = outdir / 'single-file.html'
    out.write_text(html, encoding='utf-8')
    print(f"merge: inlined {inlined['css']} stylesheet(s) + {inlined['js']} script(s) "
          f"-> {out} ({len(html)} chars)")
    return 0


def main() -> int:
    if len(sys.argv) < 3 or sys.argv[1] not in ('split', 'merge'):
        print(__doc__)
        return 1
    cmd, target = sys.argv[1], Path(sys.argv[2])
    outdir = Path(sys.argv[3]) if len(sys.argv) > 3 else target.parent
    if not target.exists():
        print(f"not found: {target}")
        return 1
    return split(target, outdir) if cmd == 'split' else merge(target, outdir)


if __name__ == '__main__':
    sys.exit(main())
